name: Build

on:
  push:
    tags: "*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            name: ubuntu_20
            pypi: yes
          - os: ubuntu-22.04
            name: ubuntu_22
          - os: macos-latest
            name: macos
          - os: windows-latest
            name: windows

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Compile using pyinstaller
        run: make pyinstaller

      - name: Testing built executable
        run: ./dist/minet/minet --version

      - name: Prepare release
        uses: vimtor/action-zip@v1
        with:
          files: ./dist/minet/
          dest: minet_${{ matrix.name }}.zip

      - name: Uploading release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./minet_${{ matrix.name }}.zip
          asset_name: ${{ matrix.name }}.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Build PyPi package
        run: |
          make clean
          python setup.py --version
          python setup.py sdist --format=gztar bdist_wheel
          twine check dist/*

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ matrix.pypi }}
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
